using System.Reflection;
using System.Text.Json;

namespace Airbnb.SharedKernel.Persistence;

public static class SeedData
{
    // Reads a JSON array embedded in the calling module's assembly (generated by frontend/scripts/export-seed.mts).
    public static IReadOnlyList<T> Load<T>(Assembly assembly, string fileName)
    {
        var resource = assembly.GetManifestResourceNames().SingleOrDefault(name => name.EndsWith($".Seed.{fileName}", StringComparison.Ordinal))
            ?? throw new InvalidOperationException($"Seed file '{fileName}' is not embedded in {assembly.GetName().Name}.");

        using var stream = assembly.GetManifestResourceStream(resource)!;
        return JsonSerializer.Deserialize<List<T>>(stream, JsonSerializerOptions.Web)
            ?? throw new InvalidOperationException($"Seed file '{fileName}' is empty.");
    }
}
