<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <InternalsVisibleTo Include="Airbnb.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Airbnb.ServiceDefaults\Airbnb.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Airbnb.SharedKernel\Airbnb.SharedKernel.csproj" />
    <ProjectReference Include="..\Modules\Stays\Airbnb.Modules.Stays\Airbnb.Modules.Stays.csproj" />
    <ProjectReference Include="..\Modules\Hosts\Airbnb.Modules.Hosts\Airbnb.Modules.Hosts.csproj" />
    <ProjectReference Include="..\Modules\Experiences\Airbnb.Modules.Experiences\Airbnb.Modules.Experiences.csproj" />
    <ProjectReference Include="..\Modules\Services\Airbnb.Modules.Services\Airbnb.Modules.Services.csproj" />
    <ProjectReference Include="..\Modules\Reviews\Airbnb.Modules.Reviews\Airbnb.Modules.Reviews.csproj" />
  </ItemGroup>

</Project>
